package cn.lqso.mbg.model;

import java.util.Date;

public class Alarm extends AlarmKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.alarm_date
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private Date alarmDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.org_no
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private String orgNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.alarm_type
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private Integer alarmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.read_state
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private Integer readState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.region_no
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private String regionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.create_time
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.update_time
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yxyd_alarm.alarm_msg
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    private String alarmMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.alarm_date
     *
     * @return the value of yxyd_alarm.alarm_date
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public Date getAlarmDate() {
        return alarmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.alarm_date
     *
     * @param alarmDate the value for yxyd_alarm.alarm_date
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setAlarmDate(Date alarmDate) {
        this.alarmDate = alarmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.org_no
     *
     * @return the value of yxyd_alarm.org_no
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.org_no
     *
     * @param orgNo the value for yxyd_alarm.org_no
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.alarm_type
     *
     * @return the value of yxyd_alarm.alarm_type
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public Integer getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.alarm_type
     *
     * @param alarmType the value for yxyd_alarm.alarm_type
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setAlarmType(Integer alarmType) {
        this.alarmType = alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.read_state
     *
     * @return the value of yxyd_alarm.read_state
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public Integer getReadState() {
        return readState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.read_state
     *
     * @param readState the value for yxyd_alarm.read_state
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setReadState(Integer readState) {
        this.readState = readState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.region_no
     *
     * @return the value of yxyd_alarm.region_no
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public String getRegionNo() {
        return regionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.region_no
     *
     * @param regionNo the value for yxyd_alarm.region_no
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setRegionNo(String regionNo) {
        this.regionNo = regionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.create_time
     *
     * @return the value of yxyd_alarm.create_time
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.create_time
     *
     * @param createTime the value for yxyd_alarm.create_time
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.update_time
     *
     * @return the value of yxyd_alarm.update_time
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.update_time
     *
     * @param updateTime the value for yxyd_alarm.update_time
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yxyd_alarm.alarm_msg
     *
     * @return the value of yxyd_alarm.alarm_msg
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public String getAlarmMsg() {
        return alarmMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yxyd_alarm.alarm_msg
     *
     * @param alarmMsg the value for yxyd_alarm.alarm_msg
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    public void setAlarmMsg(String alarmMsg) {
        this.alarmMsg = alarmMsg;
    }
}