package cn.lqso.mbg.mapper;

import cn.lqso.mbg.model.Alarm;
import cn.lqso.mbg.model.AlarmExample;
import cn.lqso.mbg.model.AlarmKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    long countByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int deleteByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int deleteByPrimaryKey(AlarmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int insert(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int insertSelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    List<Alarm> selectByExampleWithBLOBs(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    List<Alarm> selectByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    Alarm selectByPrimaryKey(AlarmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int updateByExample(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int updateByPrimaryKeySelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yxyd_alarm
     *
     * @mbg.generated Tue Nov 23 17:59:19 CST 2021
     */
    int updateByPrimaryKey(Alarm record);

    /**
     * 在生成的mapper中添加一个查询
     */
    int count();
}